### ISSUE TITLE
应控制数据文件大小

### ISSUE THREAD

**Issue by Wszl** [lqzhgood/Shmily-Get-QQ-PC_MHT#2]
我的mth文件1.2g，生成的html和json文件都在100M+，不利于使用
是不是应该用多个数据文件来分割一下，展示的时候也可以分别加载

**Comment by lqzhgood** [comment]
符合预期，理由参考 [Shmily-Show](https://github.com/lqzhgood/Shmily-Show)  FAQ
[Q_A.md#为什么生成的数据 json 这么大](https://github.com/lqzhgood/Shmily-Show/blob/main/docs/Q_A.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E7%94%9F%E6%88%90%E7%9A%84%E6%95%B0%E6%8D%AE-json-%E8%BF%99%E4%B9%88%E5%A4%A7)

**Comment by Wszl** [comment]
> 符合预期，理由参考 [Shmily-Show](https://github.com/lqzhgood/Shmily-Show) FAQ [Q_A.md#为什么生成的数据 json 这么大](https://github.com/lqzhgood/Shmily-Show/blob/main/docs/Q_A.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E7%94%9F%E6%88%90%E7%9A%84%E6%95%B0%E6%8D%AE-json-%E8%BF%99%E4%B9%88%E5%A4%A7)
这个issue可能导致以下问题：
1、数据文件json过大即使是本地http服务器也需要时间加载，我的chrome 8G内存的设备打开我转换的文件依旧会卡死。
2、抹杀了在github pages 等这些网站上部署的可能
我理解你说的空间换时间的做法，只不过为了更多的可能性，应该用将数据文件拆分成多个小文件，而不是一个大文件。

**Comment by lqzhgood** [comment]
- 1 的问题在 FAQ 里面已经有了 [# 性能如何] ， 性能不是问题 ，而且分割后只会降低性能
- 2 设计上就是本地部署，我不太理解把自己的隐私放公网上有什么必要？
   - 2.1 如果是 github page 部署，那么也是静态部署，小文件大文件没有区别


在纯静态的设计下，一堆小文件和一个大文件是一样的，例如 搜索等功能，必然是要全量加载数据到内存的，数据量并没有变化。

即便你要放到公网上去，也应该改写为 server 模式，使用数据库等更高效的加载方式，所以也没有拆成小文件的必要。 

所以拆成一堆小文件，除了并行下载更快，没什么实质上的好处（如性能提升等）~ 反而使程序更复杂更慢。

**Comment by Wszl** [comment]
github 不支持推送超过100M的文件，另外，小文件比起大文件的好处是可以并发加载。  用一些动态加载，分页技术，总是可以将当前使用的数据降到最小，当然我这些都只是建议。

**Comment by lqzhgood** [comment]
部署到 GitHub 没啥必要吧~ 聊天的资源文件如视频大小也可能大于100M,  整体仓库也可能大于5G

拆成小文件搜索也做不了了

好处也仅仅是第一次加载快一些

弊大于利
